### ISSUE TITLE
most likely a false positive from windows defender but curious what would be causing this 

### ISSUE THREAD

**Issue by Mezque** [builtbybel/LoveWindowsAgain#1]
Just to let you know, its being flagged by windows defenders real time protection as `Trojan:Script/Wacatac.B!ml`
<img width="364" alt="image" src="https://user-images.githubusercontent.com/31026406/171963264-03a8cfa1-7051-4f69-901f-b3f4e81e6973.png">

I'm sure it's a false positive due to the nature of how the program works but I would be happy for the source code to be released and thought I might just let you know this happens in case you were unaware of the current problem :)

**Comment by Belim** [comment]
dont know whats wrong. the answer from ms does not help us now either
https://www.microsoft.com/en-us/wdsi/submission/0fe84699-4919-40a8-bda1-89f75fc4f1d3

maybe the **Windows** in the name bothers the defender 😸

**Comment by Belim** [comment]
it's just the .zip file that has been flagged. 
i've pushed the unzipped executable to the releases.

**Comment by kataras** [comment]
@Belim even the executable is marked as unsafe and dangerous by Google Chrome.

![image](https://user-images.githubusercontent.com/22900943/172029517-656b5638-b456-4c6f-939d-fd337576e487.png)

**Comment by Belim** [comment]
This is just the SmartScreen Filter warning which should  disappear soon.

_When you download a program from the Internet, SmartScreen Filter will check the program against a list of programs that are downloaded by a significant number of other Edge users and a list of programs that are known to be unsafe. If the program you're downloading isn't on either list, SmartScreen Filter will display a warning that the file isn't "commonly downloaded." It doesn't necessarily mean the website is fraudulent or that the program is malware, but you probably shouldn't download or install the program unless you trust the website and the publisher._

**Comment by Mezque** [comment]
> @Belim even the executable is marked as unsafe and dangerous by Google Chrome.
> 
> ![image](https://user-images.githubusercontent.com/22900943/172029517-656b5638-b456-4c6f-939d-fd337576e487.png)

That's normal for chrome, as it says it's due to the fact it's not a commonly downloaded file so it doesn't recognize it.




> it's just the .zip file that has been flagged. i've pushed the unzipped executable to the releases.

Yeah strangely enough it was just the zip file as the exe file alone did not get flagged by my defender anymore lol

**Comment by Mezque** [comment]
Anyhow, thanks for the quick support :) 

Love your work @Belim glad that it got figured out :)
