### ISSUE TITLE
HiDPI issue

### ISSUE THREAD

**Issue by FadeMind** [builtbybel/LoveWindowsAgain#4]
![fged](https://user-images.githubusercontent.com/9846948/173219277-417e046f-9f79-4a5c-a9b7-043b844da8e7.png)

![20220612-1655013847](https://user-images.githubusercontent.com/9846948/173219291-7d6df0f4-30b1-4585-9e7d-93befb9619e4.png)

**Comment by Belim** [comment]
Ah, the autosize property

here it is fixed [LoveWindowsAgain_dev.zip](https://github.com/builtbybel/LoveWindowsAgain/files/8886296/LoveWindowsAgain_dev.zip)

**Comment by FadeMind** [comment]
Thanks

![fxs](https://user-images.githubusercontent.com/9846948/173245200-3c8c8faa-6e6c-48f9-8288-8943e51fa814.png)
